---
- name: install dep pkgs
  with_items:
    - tar
    - xz
    - unzip
    - curl
    - ipset
  become: yes
  become_user: root
  package: name={{item}} state=present

- name: configure SELinux policy
  become: yes
  become_user: root
  when: ansible_os_family == "RedHat"
  selinux: >-
    conf={{ dcos_selinux_conf }}
    policy={{ dcos_selinux_policy }}
    state={{ dcos_selinux_state }}

- name: add nogroup group
  become: yes
  become_user: root
  group: name=nogroup state=present
  
- name : mkdir /tmp/dcos
  file: >-
    path=/tmp/dcos
    state=directory
    mode=0755

- name: download dcos_install.sh
  get_url: >-
    url={{ dcos_bootstrap_url }}/dcos_install.sh
    dest=/tmp/dcos/dcos_install.sh
    mode=0755
    use_proxy=no

- name: deploy masters...
  become: True
  become_user: root
  ignore_errors: yes
  when: >-
    '{{dcos_bootstrap_master_group}}' in group_names
  command: ./dcos_install.sh master
  args:
    chdir: /tmp/dcos

- name: deploy private agents...
  become: True
  become_user: root
  ignore_errors: yes
  when: >-
    '{{dcos_bootstrap_private_agent_group}}' in group_names
  command: ./dcos_install.sh slave
  args:
    chdir: /tmp/dcos

- name: deploy public agents...
  become: True
  become_user: root
  ignore_errors: yes
  when: >-
    '{{dcos_bootstrap_public_agent_group}}' in group_names
  command: ./dcos_install.sh slave_public
  args:
    chdir: /tmp/dcos

- name: restart master node service discovery and proxy services to pick up changes
  become: True
  become_user: root
  when: >-
    '{{dcos_bootstrap_master_group}}' in group_names
  with_items:
    - dcos-mesos-dns
    - dcos-adminrouter
  service: name={{item}} state=restarted
